const plans = {
  12: [
    {
      id: 1,
      title: 'Premium',
      monthly_price: 199.5,
      discount: 20,
      isActive: false,
      details: [
        { id: 1, value: 'Host 5', field: 'Domain' },
        { id: 2, value: '2GB NVMe', field: 'Storage' },
        { id: 3, value: '50GB', field: 'Bandwidth' },
        { id: 4, value: 'Free', field: 'SSL Certificate' },
        { id: 5, value: '24/7', field: 'Support' },
        { id: 6, value: '2GB NVMe', field: 'Storage' },
        { id: 7, value: 'Free', field: 'SSL Certificate' },
      ],
    },
    {
      id: 2,
      title: 'Business',
      monthly_price: 199.5,
      discount: 70,
      isActive: true,
      details: [
        { id: 1, value: 'Host 5', field: 'Domain' },
        { id: 2, value: '2GB NVMe', field: 'Storage' },
        { id: 3, value: '50GB', field: 'Bandwidth' },
        { id: 4, value: 'Free', field: 'SSL Certificate' },
        { id: 5, value: '24/7', field: 'Support' },
        { id: 6, value: '2GB NVMe', field: 'Storage' },
        { id: 7, value: 'Free', field: 'SSL Certificate' },
      ],
    },
    {
      id: 3,
      title: 'Online Store',
      monthly_price: 199.5,
      discount: 30,
      isActive: false,
      details: [
        { id: 1, value: 'Host 5', field: 'Domain' },
        { id: 2, value: '2GB NVMe', field: 'Storage' },
        { id: 3, value: '50GB', field: 'Bandwidth' },
        { id: 4, value: 'Free', field: 'SSL Certificate' },
        { id: 5, value: '24/7', field: 'Support' },
        { id: 6, value: '2GB NVMe', field: 'Storage' },
        { id: 7, value: 'Free', field: 'SSL Certificate' },
      ],
    },
    {
      id: 4,
      title: 'Pro',
      monthly_price: 199.5,
      discount: 40,
      isActive: false,
      details: [
        { id: 1, value: 'Host 5', field: 'Domain' },
        { id: 2, value: '2GB NVMe', field: 'Storage' },
        { id: 3, value: '50GB', field: 'Bandwidth' },
        { id: 4, value: 'Free', field: 'SSL Certificate' },
        { id: 5, value: '24/7', field: 'Support' },
        { id: 6, value: '2GB NVMe', field: 'Storage' },
        { id: 7, value: 'Free', field: 'SSL Certificate' },
      ],
    },
  ],
  36: [
    {
      id: 1,
      title: 'Premium',
      monthly_price: 999.5,
      discount: 69,
      isActive: false,
      details: [
        { id: 1, value: 'Host 5', field: 'Domain' },
        { id: 2, value: '2GB NVMe', field: 'Storage' },
        { id: 3, value: '50GB', field: 'Bandwidth' },
        { id: 4, value: 'Free', field: 'SSL Certificate' },
        { id: 5, value: '24/7', field: 'Support' },
        { id: 6, value: '2GB NVMe', field: 'Storage' },
        { id: 7, value: 'Free', field: 'SSL Certificate' },
      ],
    },
    {
      id: 2,
      title: 'Business',
      monthly_price: 1259,
      discount: 10,
      isActive: false,
      details: [
        { id: 1, value: 'Host 5', field: 'Domain' },
        { id: 2, value: '2GB NVMe', field: 'Storage' },
        { id: 3, value: '50GB', field: 'Bandwidth' },
        { id: 4, value: 'Free', field: 'SSL Certificate' },
        { id: 5, value: '24/7', field: 'Support' },
        { id: 6, value: '2GB NVMe', field: 'Storage' },
        { id: 7, value: 'Free', field: 'SSL Certificate' },
      ],
    },
    {
      id: 3,
      title: 'Online Store',
      monthly_price: 10000,
      discount: 40,
      isActive: true,
      details: [
        { id: 1, value: 'Host 5', field: 'Domain' },
        { id: 2, value: '2GB NVMe', field: 'Storage' },
        { id: 3, value: '50GB', field: 'Bandwidth' },
        { id: 4, value: 'Free', field: 'SSL Certificate' },
        { id: 5, value: '24/7', field: 'Support' },
        { id: 6, value: '2GB NVMe', field: 'Storage' },
        { id: 7, value: 'Free', field: 'SSL Certificate' },
      ],
    },
    {
      id: 4,
      title: 'Pro',
      monthly_price: 100,
      discount: 9,
      isActive: false,
      details: [
        { id: 1, value: 'Host 5', field: 'Domain' },
        { id: 2, value: '2GB NVMe', field: 'Storage' },
        { id: 3, value: '50GB', field: 'Bandwidth' },
        { id: 4, value: 'Free', field: 'SSL Certificate' },
        { id: 5, value: '24/7', field: 'Support' },
        { id: 6, value: '2GB NVMe', field: 'Storage' },
        { id: 7, value: 'Free', field: 'SSL Certificate' },
      ],
    },
  ],
};

export const loadPlans = (months) => {
  return plans[months];
};
